import { createFileRoute, Link } from "@tanstack/react-router";

import { BacktestPanel, ElasticityChart, IndexChart } from "@/components/apix/charts";
import { Heatmap, RoutesTable } from "@/components/apix/tables";
import { Delta, Panel } from "@/components/apix/ui";
import {
  getBacktest,
  getHeatmap,
  getIndexHistory,
  getLatestIndex,
  getRoutesLatest,
  getWeeklyIndex,
} from "@/lib/apix-data";

const TITLE = "APIx — Real-Time Airfare Price Index for India";
const DESC =
  "A passenger-traffic weighted index of Indian domestic airfares, built CPI-style with advance-purchase windows, fare-component breakdown, spike detection and a DGCA backtest.";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  loader: () => ({
    history: getIndexHistory(),
    latest: getLatestIndex(),
    weekly: getWeeklyIndex(),
    heatmap: getHeatmap(),
    routes: getRoutesLatest(),
    backtest: getBacktest(),
  }),
  component: Dashboard,
});

function Dashboard() {
  const { history, latest, weekly, heatmap, routes, backtest } = Route.useLoaderData();
  const weekChange = weekly[weekly.length - 1]?.pct_change ?? 0;
  const spikeDays = history.filter((d) => d.spikes.length > 0).length;

  return (
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:py-10">
      <header className="panel mb-5 p-5 sm:p-6">
        <div className="flex flex-wrap items-start justify-between gap-6">
          <div>
            <div className="label-xs">SIH26056 · MoSPI prototype</div>
            <h1 className="mt-2 text-2xl font-bold sm:text-3xl">
              APIx — Real-Time Airfare Price Index
            </h1>
            <p className="mt-2 max-w-xl text-sm text-muted-foreground">
              Passenger-traffic weighted index of Indian domestic airfares, computed the way the
              CPI is: fixed weights, fixed baskets, transparent methodology.
            </p>
          </div>
          <div className="text-right">
            <div className="label-xs">Index · {latest.date}</div>
            <div className="num mt-1 text-5xl font-bold leading-none text-primary">
              {latest.index_value.toFixed(2)}
            </div>
            <div className="mt-2 flex justify-end">
              <Delta value={latest.pct_change} big />
            </div>
          </div>
        </div>

        <div className="mt-5 grid gap-3 sm:grid-cols-4">
          {[
            { k: "Week change", v: `${weekChange > 0 ? "+" : ""}${weekChange.toFixed(2)}%` },
            { k: "Routes tracked", v: String(heatmap.length) },
            { k: "Spike days (90d)", v: String(spikeDays) },
            { k: "DGCA deviation", v: `${backtest.summary.avg_abs_deviation_pct}%` },
          ].map((s) => (
            <div key={s.k} className="rounded-lg bg-surface-2 px-3 py-2.5">
              <div className="label-xs">{s.k}</div>
              <div className="num mt-0.5 text-lg font-semibold">{s.v}</div>
            </div>
          ))}
        </div>

        <nav className="mt-5 flex gap-2">
          <Link
            to="/methodology"
            className="rounded-md border border-border px-3 py-1.5 text-xs font-medium hover:bg-surface-2"
          >
            Methodology
          </Link>
          <a
            href="/api/index/weekly"
            className="rounded-md border border-border px-3 py-1.5 text-xs font-medium hover:bg-surface-2"
          >
            CPI-ready API
          </a>
        </nav>
      </header>

      <div className="grid gap-5">
        <IndexChart history={history} />

        <div className="panel border-l-4 border-l-accent p-4 sm:p-5">
          <div className="label-xs">Auto-generated explanation</div>
          <p className="mt-2 text-sm leading-relaxed sm:text-base">{latest.explanation_text}</p>
          <p className="mt-2 text-xs text-muted-foreground">
            Top contributor: {latest.top_contributor_route} · generated by
            <span className="num"> calculate_index.py</span>
          </p>
        </div>

        <Heatmap rows={heatmap} />

        <div className="grid gap-5 lg:grid-cols-2">
          <ElasticityChart />
          <Panel
            title="Weekly CPI-ready series"
            subtitle="Aggregated for NSO / RBI consumption via GET /api/index/weekly."
          >
            <div className="max-h-[300px] overflow-y-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border">
                    <th className="label-xs px-2 py-2 text-left">Week of</th>
                    <th className="label-xs px-2 py-2 text-right">Index</th>
                    <th className="label-xs px-2 py-2 text-right">Change</th>
                  </tr>
                </thead>
                <tbody>
                  {[...weekly].reverse().map((w) => (
                    <tr key={w.week_start} className="border-b border-border/60">
                      <td className="num px-2 py-2">{w.week_start}</td>
                      <td className="num px-2 py-2 text-right">{w.index_value.toFixed(2)}</td>
                      <td className="px-2 py-2 text-right">
                        <Delta value={w.pct_change} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Panel>
        </div>

        <BacktestPanel backtest={backtest} />
        <RoutesTable date={routes.date} fares={routes.fares} />
      </div>

      <footer className="mt-8 text-xs text-muted-foreground">
        Prototype data is simulated for demonstration. Production path: approved data-sharing APIs
        with airlines, OTAs and DGCA. See the methodology page for weighting and ethical-collection
        details.
      </footer>
    </div>
  );
}
